feat: allow to screenshoot custom area
gemini-testing/gemini-core pull request #105
Opened 2021-12-09 12:57 UTC by OldSkyTree

WIP

2022-01-17 11:50 UTC, DudaGod requested changes

2022-01-17 11:50 UTC, DudaGod commented on lib/browser/client-scripts/index.js
> +    var areaForScreenshot = opts.areaForScreenshot;
Договаривались реализовать не через опции, а что можно будет вместо `selectors` передать необходимый объект с координатами.

2022-01-24 13:50 UTC, OldSkyTree commented on lib/browser/client-scripts/index.js
> +    var areaForScreenshot = opts.areaForScreenshot;
исправил

2022-02-08 13:48 UTC, DudaGod requested changes
Давай API немножко поменяем.

2022-02-08 17:01 UTC, OldSkyTree commented on lib/browser/client-scripts/index.js
> +exports.prepareScreenshot = function prepareScreenshot(selectorsOrArea, opts) {
Не совсем уверен, для чего может пригодиться передавать несколько областей. Все равно их придется мерджить, так пускай этим озаботятся где-то снаружи.

Тот массив селекторов как раз и преобразуется в один rect.

2022-02-08 17:23 UTC, DudaGod commented on lib/browser/client-scripts/index.js
> +exports.prepareScreenshot = function prepareScreenshot(selectorsOrArea, opts) {
> Не совсем уверен, для чего может пригодиться передавать несколько областей. Все равно их придется мерджить, так пускай этим озаботятся где-то снаружи.

Может кому-то не хочется самому считать, а хочется скормить в `prepareScreenshot` несколько областей с координатами и пусть он сам с ними возится. Ну и текущее API у нас работает тоже с массивом. Поэтому, кажется, что довольно дешево можно такую возможность поддержать. Все запчасти у нас для этого есть.

> Тот массив селекторов как раз и преобразуется в один rect.

Ну да и тут в случае передачи нескольких областей тоже получим один rect.

2022-02-08 17:27 UTC, OldSkyTree commented
запушил с форсом, так как раньше уже успел отребейзится по мастеру

2022-02-08 17:30 UTC, OldSkyTree commented on lib/browser/client-scripts/index.js
> +    if (Rect.isRect(selectorsOrArea)) {
Мне кажется в конструкторе не совсем то, что нужно. Там бросается ошибка, так как текущих данных недостаточно для построения `rect`. А функцию `isRect` добавил, так как мне показалось это полным решением, чем просто проверять на то, что это объект.

2022-03-02 15:16 UTC, DudaGod approved these changes

2022-03-03 11:18 UTC, merged