feat(sets-builder): Throw error if no file matched path (#85)
gemini-testing/gemini-core pull request #87
Opened 2020-12-01 23:04 UTC by Glazomer

## Commits:
1. Added file to the test, so will not fail in new feature is implemented
2. Added failing test.
3. Added new feature. Now all tests are passed.

2020-12-02 08:06 UTC, DudaGod requested changes
Есть проблемы еще.

2020-12-02 08:08 UTC, DudaGod commented
Да и это больше на `fix` матчится, а не на `feat`.

2020-12-02 08:32 UTC, Glazomer commented on lib/sets-builder/index.js
> +            throw new Error('Could not find a single file matched by masks! (probably a typo in paths to files)');
Да, я тоже думал как это написать, в итоге подумал что (probably typo) должно сразу дать понять, откуда ноги растут.
Да, если в ошибке указать переданные пути, то должно сразу стать понятным, где ошибка

2020-12-02 09:55 UTC, Glazomer commented on lib/sets-builder/index.js
> +        if (!_.isEmpty(this._filesToUse) && _.isEmpty(filesToUse)) {
Ок. Когда я спрашивал "Вынести в отдельный `.then()`, я это и имел ввиду. Походу плохо объяснил что хотел сделать."

2020-12-02 09:56 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +        it('should throw an error if all paths are not valid', () => {
Ну, ок, спорить не буду.

2020-12-02 15:33 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            const globOpts = sandbox.stub(TestSet.prototype, 'useFiles');
`var stub = sinon.stub(object, "method");`
Replaces object.method with a stub function. An exception is thrown if the property is not already a function.

`sandbox.stub();`
Works almost exactly like sinon.stub, only also adds the returned stub to the internal collection of fakes for easy restoring through sandbox.restore().

2020-12-02 15:33 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            const globOpts = sandbox.stub(TestSet.prototype, 'useFiles');
Ок, т.е. нам это не надо, понял

2020-12-02 15:40 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            const globOpts = sandbox.stub(TestSet.prototype, 'useFiles');
Вернее не "не надо", а наоборот, это вредит нам.

2020-12-02 16:16 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            sandbox.stub(TestSet.prototype, 'useFiles');
Нет, теперь разобрался, 😅. Мы никак не будем использовать стаб

2020-12-02 16:18 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            return assert.isRejected(createSetBuilder()
Да, знаю что любую. Так просто в тестах выше было. А как именно предлагаете использовать async/await? Вместе с try/catch?

2020-12-02 18:44 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +            return assert.isRejected(createSetBuilder()
Исправил эту проблему, передаю RegExp для проверки теперь.
Думаю `async/await` не стоит использовать, т.к. нигде нет его, а `assert.isRejected` используется

2020-12-07 18:16 UTC, DudaGod approved these changes
Нужно еще коммиты сосквошить.

2020-12-07 18:16 UTC, DudaGod commented on lib/sets-builder/index.js
> +        return filesToUse;
nit: я бы пустой строкой отбил

2020-12-07 18:16 UTC, DudaGod commented on test/lib/sets-builder/index.js
> +            return assert.isRejected(createSetBuilder()
Да, можно было через `try/catch`, но так тоже пойдет.

2020-12-14 09:08 UTC, DudaGod commented on test/lib/sets-builder/index.js
> +                .useFiles(['some/files/fiel.js'])
У тебя тут получилось, что маску указали `some/*/fiel.js`, а использовали пути по адресу `some/files/fiel.js`. Маска - `some/*/fiel.js` на путь `some/files/fiel.js` матчится. И соответственно не понятно почему `expandFiles` возвращает пустой массив.

Здесь необходимо явно указать или маску другую или путь. Чтобы они друг на друга никак не могли сматчится. Обычно указывают `some/files` и `another/files`.

2020-12-14 09:08 UTC, DudaGod commented on lib/sets-builder/index.js
> +        if (!_.isEmpty(this._filesToUse) && _.isEmpty(filesToUse)) {
сложно читать конструкцию когда в ней присутствуют две очень похожие переменные - `this._filesToUse` - это по сути маски указанные и `filesToUse` - это найденные-раскрытые пути до файлов. Предлагаю второй `filesToUse` переименовать во что-то более понятное, например в `expandedFiles`.

2020-12-14 09:08 UTC, DudaGod commented on lib/sets-builder/index.js
> +        return filesToUse;
Давай все таки отобьем пустой строкой. Некрасиво же липить друг к другу.

2020-12-15 22:18 UTC, Glazomer commented on test/lib/sets-builder/index.js
> +                .useFiles(['some/files/fiel.js'])
Да, у меня на самом деле не логично написано.
Проблема в том, зачем тогда вообще делать `globExtra.expandPaths.withArgs` если мы её не вызываем

Сейчас я сделаю проще.

2021-01-11 21:17 UTC, DudaGod commented on package.json
> +  "version": "6.1.0",
руками версию править не нужно

2021-01-11 21:17 UTC, DudaGod commented on test/lib/sets-builder/index.js
> +        it('should throw an error if no files were found with specified masks', () => {
Этот тест имеет сайд эффекты. Ты в нем явно не указываешь, что возвращает метод `expandFiles` из-за этого этот тест осозновать значительно сложнее. Прошлый его вариант был намного понятнее и очевиднее.

2021-01-14 18:37 UTC, DudaGod commented
I will merge it here - https://github.com/gemini-testing/gemini-core/pull/89.
Thank you.

2021-01-14 18:37 UTC, closed without merging

2021-01-15 14:17 UTC, Glazomer commented on package.json
> +  "version": "6.1.0",
Странно, я не трогал версию